FROM opensuse/leap:15.6
RUN zypper install -y cmake make gcc9-c++ git perl 'perl(IPC::Cmd)' rpm-build r>
    zypper clean -a
RUN useradd -m -s /bin/bash -U rpmbuild
USER rpmbuild
WORKDIR /home/rpmbuild
RUN rpmdev-setuptree
